# Generated by Django 2.0.7 on 2018-07-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_register_con_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='con_password',
        ),
    ]
