# Generated by Django 2.0.7 on 2018-07-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20180724_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='con_password',
            new_name='confirmation_pass',
        ),
    ]
