# Generated by Django 2.0.7 on 2018-07-25 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20180724_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
